In [1]:
import pandas as pd

books = pd.DataFrame({
    "Назва": ["Book A", "Book B", "Book C", "Book D", "Book E", "Book F"],
    "Автор": ["Author 1", "Author 2", "Author 3", "Author 4", "Author 5", "Author 6"],
    "Рік видання": [2010, 2018, 2020, 2015, 2022, 2017],
    "Ціна": [250, 300, 450, 200, 500, 350]
})

display(books)

average_price = books["Ціна"].mean()
print("Середня ціна:", average_price)

books_after_2015 = books[books["Рік видання"] > 2015]
display(books_after_2015)

sorted_books = books.sort_values(by="Ціна")
display(sorted_books)

    Назва     Автор  Рік видання  Ціна
0  Book A  Author 1         2010   250
1  Book B  Author 2         2018   300
2  Book C  Author 3         2020   450
3  Book D  Author 4         2015   200
4  Book E  Author 5         2022   500
5  Book F  Author 6         2017   350

Середня ціна: 341.6666666666667

    Назва     Автор  Рік видання  Ціна
1  Book B  Author 2         2018   300
2  Book C  Author 3         2020   450
4  Book E  Author 5         2022   500
5  Book F  Author 6         2017   350

    Назва     Автор  Рік видання  Ціна
3  Book D  Author 4         2015   200
0  Book A  Author 1         2010   250
1  Book B  Author 2         2018   300
5  Book F  Author 6         2017   350
2  Book C  Author 3         2020   450
4  Book E  Author 5         2022   500

In [2]:
import pandas as pd

orders = pd.DataFrame({
    "Номер замовлення": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "Клієнт": ["Ivan", "Anna", "Ivan", "Oleh", "Anna", "Maria", "Ivan", "Oleh", "Maria", "Anna", "Ivan", "Maria"],
    "Дата": ["2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04", "2024-01-05", "2024-01-06",
             "2024-01-07", "2024-01-08", "2024-01-09", "2024-01-10", "2024-01-11", "2024-01-12"],
    "Сума": [1200, 800, 1500, 600, 2200, 900, 1300, 700, 1600, 1100, 2000, 1000]
})

orders.to_csv("orders.csv", index=False)

df = pd.read_csv("orders.csv")

display(df.head(10))

orders_count = df["Клієнт"].value_counts()
print("Кількість замовлень кожного клієнта:")
print(orders_count)

print("Максимальна сума:", df["Сума"].max())
print("Мінімальна сума:", df["Сума"].min())
print("Загальна сума:", df["Сума"].sum())

   Номер замовлення Клієнт        Дата  Сума
0                 1   Ivan  2024-01-01  1200
1                 2   Anna  2024-01-02   800
2                 3   Ivan  2024-01-03  1500
3                 4   Oleh  2024-01-04   600
4                 5   Anna  2024-01-05  2200
5                 6  Maria  2024-01-06   900
6                 7   Ivan  2024-01-07  1300
7                 8   Oleh  2024-01-08   700
8                 9  Maria  2024-01-09  1600
9                10   Anna  2024-01-10  1100

Кількість замовлень кожного клієнта:
Клієнт
Ivan     4
Anna     3
Maria    3
Oleh     2
Name: count, dtype: int64
Максимальна сума: 2200
Мінімальна сума: 600
Загальна сума: 14900

In [3]:
import pandas as pd

products = pd.DataFrame({
    "Продукт": ["Apple", "Banana", "Chicken", "Rice", "Bread", "Cheese", "Milk", "Eggs", "Potato", "Fish"],
    "Категорія": ["Fruit", "Fruit", "Meat", "Grain", "Bakery", "Dairy", "Dairy", "Protein", "Vegetable", "Meat"],
    "Калорії": [52, 89, 335, 360, 265, 402, 60, 155, 77, 206],
    "Білки": [0.3, 1.1, 27, 7, 9, 25, 3.2, 13, 2, 22]
})

display(products)

high_calories = products[products["Калорії"] > 300]
display(high_calories)

average_protein = products.groupby("Категорія")["Білки"].mean()
print("Середня кількість білків за категоріями:")
print(average_protein)

sorted_products = products.sort_values(by="Калорії", ascending=False)
display(sorted_products)

   Продукт  Категорія  Калорії  Білки
0    Apple      Fruit       52    0.3
1   Banana      Fruit       89    1.1
2  Chicken       Meat      335   27.0
3     Rice      Grain      360    7.0
4    Bread     Bakery      265    9.0
5   Cheese      Dairy      402   25.0
6     Milk      Dairy       60    3.2
7     Eggs    Protein      155   13.0
8   Potato  Vegetable       77    2.0
9     Fish       Meat      206   22.0

   Продукт Категорія  Калорії  Білки
2  Chicken      Meat      335   27.0
3     Rice     Grain      360    7.0
5   Cheese     Dairy      402   25.0

Середня кількість білків за категоріями:
Категорія
Bakery        9.0
Dairy        14.1
Fruit         0.7
Grain         7.0
Meat         24.5
Protein      13.0
Vegetable     2.0
Name: Білки, dtype: float64

   Продукт  Категорія  Калорії  Білки
5   Cheese      Dairy      402   25.0
3     Rice      Grain      360    7.0
2  Chicken       Meat      335   27.0
4    Bread     Bakery      265    9.0
9     Fish       Meat      206   22.0
7     Eggs    Protein      155   13.0
1   Banana      Fruit       89    1.1
8   Potato  Vegetable       77    2.0
6     Milk      Dairy       60    3.2
0    Apple      Fruit       52    0.3

In [4]:
import pandas as pd

employees = pd.DataFrame({
    "Ім'я": ["Ivan", "Anna", "Oleh", "Maria", "Ivan", "Anna", "Oleh", "Maria"],
    "Проект": ["Project A", "Project B", "Project A", "Project C", "Project B", "Project A", "Project C", "Project B"],
    "Години": [10, 15, 20, 12, 18, 14, 16, 11]
})

display(employees)

hours_by_employee = employees.groupby("Ім'я")["Години"].sum()
print("Години за кожним співробітником:")
print(hours_by_employee)

hours_by_project = employees.groupby("Проект")["Години"].sum()
print("Години за кожним проектом:")
print(hours_by_project)

top_employee = hours_by_employee.idxmax()
print("Співробітник з найбільшою кількістю годин:", top_employee)

    Ім'я     Проект  Години
0   Ivan  Project A      10
1   Anna  Project B      15
2   Oleh  Project A      20
3  Maria  Project C      12
4   Ivan  Project B      18
5   Anna  Project A      14
6   Oleh  Project C      16
7  Maria  Project B      11

Години за кожним співробітником:
Ім'я
Anna     29
Ivan     28
Maria    23
Oleh     36
Name: Години, dtype: int64
Години за кожним проектом:
Проект
Project A    44
Project B    44
Project C    28
Name: Години, dtype: int64
Співробітник з найбільшою кількістю годин: Oleh

In [5]:
import pandas as pd

tickets = pd.DataFrame({
    "Фільм": ["Film A", "Film B", "Film C", "Film A", "Film B", "Film C", "Film A", "Film B", "Film C", "Film A", "Film B", "Film C"],
    "Місто": ["Kyiv", "Lviv", "Odesa", "Kyiv", "Lviv", "Odesa", "Kharkiv", "Kharkiv", "Kyiv", "Lviv", "Odesa", "Kharkiv"],
    "Продані квитки": [120, 90, 150, 200, 110, 130, 170, 140, 160, 180, 125, 155]
})

display(tickets)

tickets_by_film = tickets.groupby("Фільм")["Продані квитки"].sum()
print("Квитки за кожним фільмом:")
print(tickets_by_film)

tickets_by_city = tickets.groupby("Місто")["Продані квитки"].sum()
print("Квитки за кожним містом:")
print(tickets_by_city)

top_film = tickets_by_film.idxmax()
print("Фільм із найбільшою кількістю продажів:", top_film)

     Фільм    Місто  Продані квитки
0   Film A     Kyiv             120
1   Film B     Lviv              90
2   Film C    Odesa             150
3   Film A     Kyiv             200
4   Film B     Lviv             110
5   Film C    Odesa             130
6   Film A  Kharkiv             170
7   Film B  Kharkiv             140
8   Film C     Kyiv             160
9   Film A     Lviv             180
10  Film B    Odesa             125
11  Film C  Kharkiv             155

Квитки за кожним фільмом:
Фільм
Film A    670
Film B    465
Film C    595
Name: Продані квитки, dtype: int64
Квитки за кожним містом:
Місто
Kharkiv    465
Kyiv       480
Lviv       380
Odesa      405
Name: Продані квитки, dtype: int64
Фільм із найбільшою кількістю продажів: Film A

In [6]:
import pandas as pd

clients = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Ім'я": ["Ivan", "Anna", "Oleh", "Maria", "Petro"],
    "Місто": ["Kyiv", "Lviv", "Odesa", "Kharkiv", "Dnipro"]
})

orders = pd.DataFrame({
    "ID клієнта": [1, 2, 1, 3, 4, 5, 2],
    "Замовлення": ["Order 1", "Order 2", "Order 3", "Order 4", "Order 5", "Order 6", "Order 7"],
    "Вартість": [1200, 800, 1500, 600, 2200, 900, 1100]
})

display(clients)
display(orders)

merged = pd.merge(clients, orders, left_on="ID", right_on="ID клієнта")
display(merged)

result = merged.groupby("Ім'я")["Вартість"].sum().reset_index()
result.columns = ["Клієнт", "Загальна вартість"]

display(result)

   ID   Ім'я    Місто
0   1   Ivan     Kyiv
1   2   Anna     Lviv
2   3   Oleh    Odesa
3   4  Maria  Kharkiv
4   5  Petro   Dnipro

   ID клієнта Замовлення  Вартість
0           1    Order 1      1200
1           2    Order 2       800
2           1    Order 3      1500
3           3    Order 4       600
4           4    Order 5      2200
5           5    Order 6       900
6           2    Order 7      1100

   ID   Ім'я    Місто  ID клієнта Замовлення  Вартість
0   1   Ivan     Kyiv           1    Order 1      1200
1   1   Ivan     Kyiv           1    Order 3      1500
2   2   Anna     Lviv           2    Order 2       800
3   2   Anna     Lviv           2    Order 7      1100
4   3   Oleh    Odesa           3    Order 4       600
5   4  Maria  Kharkiv           4    Order 5      2200
6   5  Petro   Dnipro           5    Order 6       900

  Клієнт  Загальна вартість
0   Anna               1900
1   Ivan               2700
2  Maria               2200
3   Oleh                600
4  Petro                900